<template>
  <div class="textstuff">
    <h4 class="text-light">This project was a joint venture by Satyar Foroughi and Arshia Pessaran, two data science students at the University of Central Florida. As an experiment in Natural Language Processing (NLP), it explores the use of a Recurrent Neural Network to predict the chance that input text was generated by ChatGPT's conversational language model. <br> <br> 

The RNN model was trained on a database of ChatGPT generated text responses given by HuggingFace. Since the creation of the model, variations in the ChatGPT responses may reduce the precision of our model's prediction. It works best when the input text is greater than 600 characters. <br> <br> 

Still, given the nature of this task, detection of ChatGPT generated text is a complex and imprecise task, and the model's prediction is prone to error. <br> <br> 

Give it a try, copy this text and paste it in the text-box and see how it was generated! <br> <br>

UI made by James Latimer.
</h4>
  </div>
</template>

<style scoped>
.textstuff{
  text-align: left !important;
  margin-left: 400px;
  margin-right: 600px;
  margin-top: 5% !important;
}
</style>